language: c
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
install:
  - [[ "$(uname -s)" != "Darwin" ]] || sudo apt-get -qqy update
  - [[ "$(uname -s)" != "Darwin" ]] || sudo apt-get -qqy install automake autoconf libtool pkg-config 
  - [[ "$(uname -s)" != "Darwin" ]] || sudo apt-get -qqy install libsnmp-dev libxml2-dev libjansson-dev libevent-dev libreadline-dev libbsd-dev check
  - [[ "$(uname -s)" == "Darwin" ]] && brew update
  - [[ "$(uname -s)" == "Darwin" ]] && brew install pkg-config autoconf automake libtool
  - [[ "$(uname -s)" == "Darwin" ]] && brew install readline libevent net-snmp jansson libxml2 check
script: ./autogen.sh && ./configure $LLDPD_CONFIG_ARGS && make && make check && make distcheck && sudo make install
env:
  - LLDPD_CONFIG_ARGS=""
  - LLDPD_CONFIG_ARGS="--with-embedded-libevent"
  - LLDPD_CONFIG_ARGS="--disable-privsep --with-snmp"
  - LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json --disable-lldpmed --disable-dot1 --disable-dot3"
