language: c
os: linux
dist: trusty
compiler: gcc
sudo: require
install:
  - ./tests/ci/install.sh
script:
  - ./tests/ci/run.sh
env:
  matrix:
    - LLDPD_CONFIG_ARGS=""
    - LLDPD_CONFIG_ARGS="--with-embedded-libevent"
    - LLDPD_CONFIG_ARGS="--disable-privsep --with-snmp"
    - LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json --disable-lldpmed --disable-dot1 --disable-dot3 --disable-custom"
    - LLDPD_CONFIG_ARGS="--enable-oldies"
matrix:
  include:
    - os: linux
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json"
    - os: osx
      compiler: clang
      env: LLDPD_CONFIG_ARGS="--with-snmp --with-xml --with-json"
