language: "python"
install:
  - "sudo aptitude -y -q install automake autoconf libtool pkg-config"
  - "sudo aptitude -y -q install libsnmp-dev libxml2-dev check"
script: "./autogen.sh && ./configure $LLDPD_CONFIG_ARGS && make && make check"
env:
  - LLDPD_CONFIG_ARGS=""
  - LLDPD_CONFIG_ARGS="--disable-lldpmed"
  - LLDPD_CONFIG_ARGS="--disable-dot1"
  - LLDPD_CONFIG_ARGS="--disable-dot3"
  - LLDPD_CONFIG_ARGS="--with-snmp"
branches:
  only:
    - master
    - branch-0.5
